
export enum Character {
    O_CHAR = 79,
    O_CHAR_STR = "o",
    K_CHAR = 75,
    ARROW_LEFT = 37,
    ARROW_LEFT_STR = "ArrowLeft",
    ARROW_UP = 38,
    ARROW_RIGHT = 39,
    ARROW_RIGHT_STR = "ArrowRight",
    ARROW_DOWN = 40,
    SLASH_CHAR = 191,
    ENTER = 13,
    ESCAPE = 27,
}

export enum KeyCombination {
    MOD_SHIFT_O = "mod+shift+o",
    ALT_SHIFT_O = "alt+shift+o",
    MOD_SHIFT_K = "mod+shift+k",
    ALT_SHIFT_K = "alt+shift+k",
    MOD_SHIFT_LEFT = "mod+shift+left",
    ALT_SHIFT_LEFT = "alt+shift+left",
    MOD_SHIFT_UP = "mod+shift+up",
    ALT_SHIFT_UP = "alt+shift+up",
    MOD_SHIFT_RIGHT = "mod+shift+right",
    ALT_SHIFT_RIGHT = "alt+shift+right",
    MOD_SHIFT_DOWN = "mod+shift+down",
    ALT_SHIFT_DOWN = "alt+shift+down",
    MOD_SHIFT_SLASH = "mod+shift+/",
    ALT_SHIFT_SLASH = "alt+shift+/",
    ESCAPE = "escape",
    ENTER = "enter",
    MOD_SHIFT_ESCAPE = "mod+shift+escape",
    ALT_SHIFT_ESCAPE = "alt+shift+escape",
}
